apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-public
  namespace: default
  labels:
    app: nginx-public
  annotations:
    source_url: "__CI_PROJECT_URL__"
spec:
  replicas: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx-public
  template:
    metadata:
      name: nginx-public
      labels:
        app: nginx-public
      annotations:
        source_url: "__CI_PROJECT_URL__"
    spec:
      restartPolicy: Always
      containers:
        - name: app
          image: nginx:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80
