# NodePort
apiVersion: v1
kind: Service
metadata:
  name: nginx-public
  namespace: default
  annotations:
    source_url: "__CI_PROJECT_URL__"
spec:
  type: ClusterIP
  selector:
    app: nginx-public
  ports:
    - port: 80
      targetPort: 80
